default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: project_cws_development
test:
  <<: *default
  database: project_cws_test
production:
  <<: *default
  database: project_cws_production
  username: project_cws
  password: <%= ENV['PROJECT_CWS_DATABASE_PASSWORD'] %>
